### ISSUE TITLE
New-SCSMRequestOffering : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by noaboa97** [SMLets/SMLets#19]
So I know you said, that you are not actively maintaing this repo anymore.

I wanted to create a new request offering via powershell. And I get this error:

```New-SCSMRequestOffering : Object reference not set to an instance of an object.
At line:1 char:5
+     New-SCSMRequestOffering -Title $servicename -ManagementPack $mgmt ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SCSMRequestOffering], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,SMLets.NewSCSMRequestOfferingCommand
```

  

```PS C:\WINDOWS\system32> $error[0] | select-object *


PSMessageDetails      : 
Exception             : System.NullReferenceException: Object reference not set to an instance of an object.
                           at SMLets.NewSCSMRequestOfferingCommand.ProcessRecord() in F:\Visual Studio\SCSMSolutions\SMLets\SMLets.Shared\Code\Offering.cs:line 452
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [New-SCSMRequestOffering], NullReferenceException
FullyQualifiedErrorId : System.NullReferenceException,SMLets.NewSCSMRequestOfferingCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

If I'm correct the only madatory parameters are `-Title` and `-ManagementPack`

Titel is a String and the ManagepentPack the object I request with `Get-SCSMManagementPack -Name $mgmtpackname`

Is this an Issue of the cmdlet `New-SCSMRequestOffering`?

**Comment by AdhocAdam** [comment]
I could be wrong here, but at a minimum you'll probably want:
- The Template the RO targets
- Title/Description of the RO
- Status of the RO (e.g. Draft or Published)
- The Management Pack the RO is saved to (keep with the Template to respect console/SDK behavior)
- At least 1 question/input

That said, the following PowerShell will construct a Request Offering with a single prompt of type String, mapped to the Description property of the Template.

```powershell
$mp = Get-SCManagementPack -Name "ManagementPack.c66fd80cae4d4986a0d9c1457fc07512" #the MP that contains the Template and eventual storage of the Request Offering
$roStatusDraft = Get-SCSMEnumeration -Name "System.Offering.StatusEnum.Draft$"
$roStatusPublish = Get-SCSMEnumeration -Name "System.Offering.StatusEnum.Published$"
$template = Get-SCSMObjectTemplate -DisplayName "pwsh ro template"  #the Template that's already been created. I'm using a Service Request.
$question = New-SCSMRequestOfferingQuestion -Prompt "enter some text" -TargetPath "Description" -Type "String" #an input seen on the User/Configure prompts sections of an RO

New-SCSMRequestOffering -TargetTemplate $template -Title "Pwsh Request Offering" -BriefDescription "created from powershell" -Status $roStatusDraft -DisplayName "roDisplay" -ManagementPack $mp -Questions $question
```

**Comment by noaboa97** [comment]
Thank you for your reply. 
I will check on monday when I‘m back at work.

Before I create the RO I do indeed create the mp and the template. But I couldn‘t figure out what else it needed. Like the $question or the status. Couldn‘t find any documentation on that.

**Comment by antonGritsenko** [comment]
@noaboa97 based on the error you had, the issue is empty Questions parameter. 
This cmdlet is very old and, to be honest, was never tested very well and most of the docs are missing. Questions parameter must be mandatory.

**Comment by noaboa97** [comment]
Thank you very much. Now I can create the RO.
So the Questions parameter is mandatory.

Now I can't figure out how to set the promt type to "Query Results" and then configure the promt,

On my current template if I set it over the client app to query results in powershell it will show `SourceControlType : string`
Can I somehow do that with `-QueryOption` on `New-SCSMRequestOfferingQuestion` or is that just not possible because the stringmapper isn't up to date?

**Comment by antonGritsenko** [comment]
To be honest, I never using this cmdlet because it bring limitation instead helping with some. You can create request offering object directly using object projection. But it a bit more complex to describe in just one comment. Can I ask why do you want to do this in PowerShell but not in XML?
